Update to work with psc-0.15.7-20230207
thomashoneyman/purescript-halogen-portal pull request #6
Opened 2023-02-10 00:33 UTC by flip111

https://github.com/thomashoneyman/purescript-halogen-portal/issues/5#issuecomment-1424825638

2023-02-10 01:43 UTC, thomashoneyman requested changes

2023-02-10 01:43 UTC, thomashoneyman commented on example/Example/Component/Child.purs
> +import Prelude
Could you move this back to the top of the import list?

2023-02-10 01:43 UTC, thomashoneyman commented on example/Example/Component/Parent.purs
> +import Prelude
Same here — I'd prefer the unqualified import go at the top.

2023-02-10 01:43 UTC, thomashoneyman commented on packages.dhall
> +-------------------------------
Could you remove this comment, leaving just the `upstream` code?

2023-02-10 01:43 UTC, thomashoneyman commented on spago.dhall
> +-}
```suggestion
```

2023-02-10 01:43 UTC, thomashoneyman commented on src/Halogen/Portal.purs
> +import Prelude
Could you move this to the top of the import list?

2023-02-10 01:43 UTC, thomashoneyman commented on src/Halogen/Portal.purs
> +newtype NT :: forall k. (k -> Type) -> (k -> Type) -> Type
This is meant to be used with monads, so there's no need to be polymorphic in `k`.

```suggestion
newtype NT :: (Type -> Type) -> (Type -> Type) -> Type
```

2023-02-10 01:43 UTC, thomashoneyman commented
I have some minimal comments, but otherwise :+1: this looks good! Thanks!

2023-02-10 11:29 UTC, flip111 commented
Reference to nix also has to removed from readme

2023-02-10 11:30 UTC, flip111 commented
The dependency to `halogen-storybook` is it really necessary to do that way? Everyone using halogen-portal will pull in this dep, no ?

2023-02-10 12:50 UTC, thomashoneyman commented
> The dependency to `halogen-storybook` is it really necessary to do that way? Everyone using halogen-portal will pull in this dep, no ?

Yea we should really have a spago.example.dhall that contains dependencies for the examples, and you run the build with spago build -x spago.example.dhall

2023-02-10 16:47 UTC, thomashoneyman commented
Once we get the CI failure fixed I'm happy to merge.

```
[1/1 ModuleNotFound] example/Main.purs:10:1

  10  import Halogen.Storybook (Stories, proxy, runStorybook)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Halogen.Storybook was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

2023-02-10 21:35 UTC, merged

2023-02-11 00:09 UTC, flip111 commented
Thanks for the merge and help with the review, it's cool !